config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :plays
  resources :genres
  resources :songs
  resources :artists

  get '/artistlogin', to: 'artist_auth#artist_login', as: 'artist_login'
  post '/artistlogin', to: 'artist_auth#verify_artist'

  get '/artists/:id/logout', to: 'artist_auth#logout', as: 'artist_logout'
  
  get '/artists/:id/home', to: 'artists#home', as: 'home'

  get '/login', to: 'auth#login', as: 'login'
  post '/login', to: 'auth#verify_username'

  get '/logout', to: 'auth#logout', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    has_many :genres, through: :songs

    has_secure_password

    validates :name, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :songs
    has_many :artists, through: :songs
end

app/models/play.rb
class Play < ApplicationRecord
    belongs_to :user
    belongs_to :song

    def self.total_plays(song, user_id)
        all_plays = Play.where(song_id: song.id, user_id: user_id)
        # byebug
        if !all_plays.empty?
            all_plays.sum { |play| play.num_plays }
        else
            return nil
        end
    end
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist
    belongs_to :genre
    has_many :plays
end

app/models/user.rb
class User < ApplicationRecord
    has_many :plays
    has_many :songs, through: :plays

    validates :age, numericality: {greater_than: 0, only_integer: true}
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :redirect_user, :logged_in?, :current_artist, :artist_logged_in?

    def logged_in?
        !!current_user
    end

    def artist_logged_in?
        !!current_user
    end

    def current_user
        user = User.find(session[:user_id]) if session[:user_id]
    end

    def redirect_user
        if !current_user
            flash[:message] = "Please login to view this data"
            redirect_to login_path
        end
    end

    def current_artist
        artist = Artist.find(session[:artist_id]) if session[:artist_id]
    end

end

app/controllers/artist_auth_controller.rb
class ArtistAuthController < ApplicationController

    def artist_login
    end

    def verify_artist

        @artist = Artist.find_by(name: params[:artist_auth][:name])

        if @artist && @artist.authenticate(params[:artist_auth][:password])
            session[:artist_id] = @artist.id
            redirect_to home_path(@artist)
        else
            flash[:message] = "Invalid username or password. Please enter the proper credentials."
            render :artist_login
        end
    end

    def logout
        session.clear
        redirect_to artist_login_path
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    before_action :find_artist, only: [:show, :edit, :update, :home]

    def index
        @artists = Artist.all
    end

    def new
        @artist = Artist.new
    end

    def create
        @artist = Artist.new(artist_params)
        if @artist.save
            redirect_to artist_login_path
        else
            flash[:message] = "Invalid entry. Please include both name and password."
            render 'new'
        end
    end

    def update
        if @artist.update(artist_params)
            redirect_to home_path
        else
            flash[:message] = "Invalid entry. Please include both name and password."
            render 'edit'
        end
    end

    private

    def artist_params
        params.require(:artist).permit(:name, :profile_link, :image, :password, :password_confirmation)
    end

    def find_artist
        @artist = Artist.find(params[:id])
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController


    def login
    end

    def verify_username
        # find username 
        # if exists, redirect to user show page
        # else sign up (user new)

        @user = User.find_by(name: params[:auth][:name])

        if @user
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash[:message] = "Invalid username. Please enter the proper credentials."
            render :login
        end

    end

    def logout
        session.clear
        redirect_to login_path
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index
        @genres = Genre.all
    end

    def show
        @genre = Genre.find(params[:id])    
    end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

    def create
        if session[:user_id]
            @play = Play.find_by(user_id: session[:user_id], song_id: params[:song_id])
            if @play
                total = @play.num_plays + 1
                @play.update(num_plays: total)
            else
                Play.create(user_id: session[:user_id], song_id: params[:song_id], num_plays: 1)
            end
            redirect_to song_path(params[:song_id])
           # redirect_to user_path(User.find(session[:user_id]))
        else
            flash[:message] = "You must login to play a song"
            redirect_to login_path
        end
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    before_action :find_song, only:[:show,:edit, :update, :destroy]
    def index
        @songs = Song.all
    end

    def new
        @song = Song.new
    end

    def create
        @song = Song.create(song_params)
        redirect_to home_path(current_artist)
    end

    def update
        @song.update(song_params)
        redirect_to home_path(current_artist)
    end

    def destroy
        @song.delete
        redirect_to home_path(current_artist)
    end

    private

    def song_params
        params.require(:song).permit(:title, :genre_id, :artist_id, :image, :sound_link, :video_link)
    end

    def find_song
        @song = Song.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        # display flash error messages if invalid
        if @user.save
            @user.save
            redirect_to login_path
        else
            flash[:message] = "Invalid entry. Please include both name and age."
            render "new"
        end
    end

    def update
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user.delete
        session.clear
        redirect_to login_path
    end

    private

    def user_params
        params.require(:user).permit(:name, :age)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artist_auth/artist_login.html.erb
<h1>Artist Login Portal</h1><br>

<% if current_artist %>
    <h3>You're logged in as "<%= current_artist.name %>." Please select an option:</h3>
        <%= button_to "View Profile", home_path(current_artist), method: :get %> <br>
        <%= button_to "Logout", artist_logout_path(current_artist), method: :get %>
<% else %>    
    <h3>Welcome to BeatDrop! Please log in:</h3><br>

    <%= flash[:message] %>
    
    <%= form_for :artist_auth do |f| %>

        <%= f.label "Name" %>
        <%= f.text_field :name %><br>

        <%= f.label "Password" %>
        <%= f.password_field :password %><br>

        <%= f.submit "Log In"%>
    <% end %>

    <br>
    <h6>Or sign up as a new artist <%= link_to "HERE", new_artist_path %></h6>
<% end %>

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>

    <%= f.label "Name" %>
    <%= f.text_field :name %><br>

    <%= f.label "Password" %>
    <%= f.password_field :password %><br>

    <%= f.label "Password Confirmation" %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Update Your Profile</h1>

<%= flash[:message] %><br>

<%= form_for @artist do |f| %>
    <%= f.label "Name" %>
    <%= f.text_field :name %><br>

    <%= f.label "Profile Image"%>
    <%= f.text_field :image %><br>

    <br>
    <%= f.label "Password" %>
    <%= f.password_field :password %><br>

    <%= f.label "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <br><br>
    <%= f.submit %>
<% end %>

app/views/artists/home.html.erb
<h1>Welcome <%=@artist.name%>!</h1>

<table style="width:80%">
    <tr>
        <th>Title</th>
        <th>Genre</th>
        <th></th>
        <th></th>
    </tr>

<% @artist.songs.each {|song| %>
    <tr>
        <td><%= song.title %></td>
        <td><%= song.genre.name %></td>
        <td><%= button_to "Edit", edit_song_path(song), method: :get %></td>
        <td><%= button_to "Delete", song, method: :delete %></td>
    </tr>
<% } %>
</table>

<br>
<br>
<br>
<br>
<%= button_to "Add Song", new_song_path, method: :get %>

app/views/artists/index.html.erb
<h1> Artist </h1>

<ul><% @artists.each {|artist| %>
    <li><%= link_to artist.name, artist %></li>
<% } %></ul>

<%# show count for number of songs associated with artist? %>


<%#= button_to "All Songs", songs_path, method: :get %><br>
<%#= button_to "All Artists", artists_path, method: :get %><br>
<%#= button_to "All Genres", genres_path, method: :get %>

app/views/artists/new.html.erb
<h1>Create An Artist Account</h1><br>
<h3>Sign Up:</h3>

<%= flash[:message] %>

<%= render 'form' %>

app/views/artists/show.html.erb
  <h1><%= "#{@artist.name}'s Songs" %></h1>
  <br>
  <img src="<%= @artist.image %>" alt="Artist Image" class="artist-image">
<br>

<table style="width:100%">
  <tr>
    <% if logged_in? %> <th>Listen</th> <% end %>
    <th>Title</th>
    <th>Genre</th>
  </tr>

<% @artist.songs.each {|song| %>
  <tr>
    <% if logged_in? %><td><%= button_to "Play", plays_path, method: :post, params: { song_id: song.id }%></td><% end %>
    <td><%= link_to song.title, song %></td>
    <td><%= link_to song.genre.name, song.genre %></td>
  </tr>
<% } %>
</table>

<br>
<br>
<br>

app/views/genres/index.html.erb
<h1> Genres </h1>

<ul><% @genres.each {|genre| %>
   <li><%= link_to genre.name, genre %></li> 
<% } %>
</ul>


<%# show most popular genres or number of songs associated in a table? %>



<%#= button_to "All Songs", songs_path, method: :get %><br>
<%#= button_to "All Artists", artists_path, method: :get %><br>
<%#= button_to "All Genres", genres_path, method: :get %>

app/views/genres/show.html.erb
<h1><%="#{@genre.name} Artists"%></h1>

<ul><% @genre.artists.each {|artist| %>
    <li><%= link_to artist.name, artist %></li>
<% } %></ul>


<%#= button_to "All Songs", songs_path, method: :get %><br>
<%#= button_to "All Artists", artists_path, method: :get %><br>
<%#= button_to "All Genres", genres_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beatdrop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ultra&display=swap">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="header sticky-top">
      <a class="nav-brand">BeatDrop</a>
      <% if !logged_in? && !current_artist %>
        <a class="nav-item" href="<%=artist_login_path%>">Artist</a>
        <a class="nav-item" href="<%=login_path%>">User</a>
      <% elsif logged_in? && !current_artist %>
        <a class="nav-item" href="<%=logout_path(current_user)%>">Logout</a>
        <a class="nav-item" href="<%=edit_user_path(current_user)%>">Settings</a>
        <a class="nav-item" href="<%=user_path(current_user)%>">My Profile</a>
      <% elsif current_artist && !logged_in? %>
        <a class="nav-item" href="<%=artist_logout_path(current_artist)%>">Logout</a>
        <a class="nav-item" href="<%=edit_artist_path(current_artist)%>">Settings</a>
        <a class="nav-item" href="<%=home_path(current_artist)%>">My Profile</a>
      <% end %>
    </nav>

    <div class="transparent">
    <%= yield %>
    </div>

    <footer class="footer">
      <a class="footer-item" href="<%=songs_path%>">All Songs</a>
      <a class="footer-item" href="<%=artists_path%>">All Artists</a>
      <a class="footer-item" href="<%=genres_path%>">All Genres</a>
    </footer>
    
    
    
  </body>
  
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>

    <%= f.hidden_field :artist_id, value: current_artist.id %><br>

    <%= f.label "Title" %>
    <%= f.text_field :title %><br>

    <%= f.label "Genre" %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name) %><br>
    
    <%= f.label "Link to Song" %>
    <%= f.text_field :sound_link %><br>

    <%= f.label "Link to Music Video" %>
    <%= f.text_field :video_link %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1> Update Song </h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1> Songs </h1>

<table style="width:50%">
  <tr>
    <% if logged_in? %><th>Listen</th><% end %>
    <th>Title</th>
    <th>Artist</th>
    <th>Genre</th>
  </tr>

<% ordered_songs = @songs.order(:title) %>
<% ordered_songs.each {|song| %>
  <tr>
    <% if logged_in? %><td><%= button_to "Play", plays_path, method: :post, params: { song_id: song.id }%></td><% end %>
    <td><%= link_to song.title, song %></td>
    <td><%= link_to song.artist.name, song.artist %></td>
    <td><%= link_to song.genre.name, song.genre %></td>
  </tr>
<% } %>
</table>


<%#= button_to "All Songs", songs_path, method: :get %><br>
<%#= button_to "All Artists", artists_path, method: :get %><br>
<%#= button_to "All Genres", genres_path, method: :get %>

app/views/songs/new.html.erb
<h1>Upload Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<h3>by <%= link_to @song.artist.name, @song.artist %></h3>
<h3>Genre: <%= link_to @song.genre.name, @song.genre %></h3>
<br>



<% if logged_in? %>
    <% if !@song.video_link.blank? %>
        <iframe width="560" height="315" src="<%= @song.video_link %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="song_media"></iframe>
        <br>
    <% end %>
    
    <% if !@song.sound_link.blank? %>
        <h3>Preview: </h3>
        <audio src="<%= @song.sound_link%>" controls></audio><br><br>
    <% end %>
<% else %>
    <h6><i>Sorry, must be logged in to view audio and video sample.</i></h6>
<% end %>

app/views/users/_form.html.erb
<%= flash[:message] %>
<br>
<%= form_for @user do |f| %>
    <%= f.label "Name" %>
    <%= f.text_field :name %><br>

    <%= f.label "Age" %>
    <%= f.number_field :age %><br>

    <%= f.submit%>
<% end %>

app/views/users/edit.html.erb
<h1>Modify Profile for "<%= @user.name %>"</h1>
<br>
<h3>Edit Profile</h3>
<%= render 'form' %>
<br>
<h3>Delete Profile</h3>
<%= button_to "Delete User", @user, method: :delete %>

app/views/users/new.html.erb
<h1>Create An User Account</h1><br>
<h3>Sign Up:</h3>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3>Age: <%= @user.age %></h3>

<br>

<% if @user.songs.empty? %>
    <h3>You haven't played any songs yet! <%= link_to "Explore", songs_path %></h3>
<% else %>
    <h3>Songs played by you:</h3>
<% end %>
<ul>

<% @user.songs.each do |song| %>
    <li><%= pluralize(Play.total_plays(song, @user.id), "play") %> - <%= link_to "'#{song.title}'", song %> by <%= link_to "'#{song.artist.name}'", artist_path(song.artist) %></li>
<% end %>

</ul>